{% set name = "napari-sam" %}
{% set version = "0.4.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-sam-{{ version }}.tar.gz
  sha256: f1f6fe177e45a217a3fd10e3a66c2f641560b9b14e940cd00d2fbebc9f65ce5f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - napari
    - napari-nifti  # Not used in source code
    - numpy
    # - magicgui  # Not used in source code
    - python >={{ python_min }}
    - pytorch >=1.7
    - qtpy
    - segment-anything
    - superqt
    - torchvision >=0.8
    - tqdm
    - vispy

test:
  imports:
    - napari_sam
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-sam
  summary: Segment anything with Meta AI's new SAM model!
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/MIC-DKFZ/napari-sam

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - Karol-G
